#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Siren App - Full version with PNG icons + cover-screen behavior
- Uses media/dark_fsc.png and media/light_fsc.png if present.
- When "cover screen" button pressed, window becomes borderless and sized to screen (overrideredirect),
  when toggled back it restores to maximized (zoomed) window (no tiny-window bug).
- Console (Windows) is hidden early so setup appears without console.
- Pygame mixer initialized after Tk root is created.
- Config saved to config.txt with language, theme, media_path.
- Keyboard shortcuts preserved: Q W E, 1 2 3, H (hold), V, S, L, I, T, F11 toggles cover-screen.
- Theme switching applied in-place (no root destroy) to avoid orphan audio channels.
- Mode switching now keeps the same siren id playing but loads it from the new mode.
"""

import os
import sys
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
import pygame
import ctypes

# Try import Pillow for PNG handling; fallback to Tk PhotoImage
try:
    from PIL import Image, ImageTk
    PIL_AVAILABLE = True
except Exception:
    PIL_AVAILABLE = False

CONFIG_FILE = "config.txt"

# -------------------------
# Config helpers
# -------------------------
def load_config():
    """Load config from CONFIG_FILE. Returns dict with keys language, theme, media_path."""
    config = {"language": None, "theme": None, "media_path": None}
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            for line in f:
                if "=" in line and not line.strip().startswith("#"):
                    k, v = line.strip().split("=", 1)
                    if k in config:
                        config[k] = v
    return config

def save_config(language, theme, media_path):
    """Save config with a developer warning header."""
    with open(CONFIG_FILE, "w", encoding="utf-8") as f:
        f.write("# ⚠️ DO NOT EDIT THIS FILE UNLESS YOU ARE A DEVELOPER.\n")
        f.write("# Manual editing may break the application.\n\n")
        f.write(f"language={language}\n")
        f.write(f"theme={theme}\n")
        f.write(f"media_path={media_path}\n")

# -------------------------
# Media folder check
# -------------------------
def ensure_media_folder(parent, config):
    """
    Ensure media folder exists. Parent is a tkinter window (hidden or visible).
    If folder missing, ask user to select. If user cancels, return empty string.
    Only save config if user selected a valid folder.
    """
    media_path = config.get("media_path") or os.path.join(os.getcwd(), "media")
    if os.path.exists(media_path) and os.path.isdir(media_path):
        return media_path

    # Ask user to select folder (dialog parented to given parent)
    messagebox.showwarning(
        "Media folder missing",
        "Media folder not found.\nPlease select your media directory.",
        parent=parent
    )
    selected = filedialog.askdirectory(title="Select Media Folder", parent=parent)
    if selected and os.path.exists(selected):
        # Save to config
        save_config(config.get("language") or "en", config.get("theme") or "light", selected)
        return selected
    else:
        messagebox.showerror(
            "Error",
            "Media folder not selected. Sounds will not work.\nYou can select it again next time.",
            parent=parent
        )
        return ""  # empty -> treated as missing

# -------------------------
# Setup (first-run)
# -------------------------
def setup_screen():
    """Language and theme selection shown only on first launch."""
    setup = tk.Tk()
    setup.title("Sireb App | First Setup")
    setup.geometry("250x230")
    setup.eval('tk::PlaceWindow . center')

    selected_lang = tk.StringVar()
    selected_theme = tk.StringVar()

    def confirm():
        lang = selected_lang.get()
        theme = selected_theme.get()
        if not lang or not theme:
            messagebox.showwarning("Missing Selection", "Please select both language and theme before continuing.")
            return
        config = {"language": lang, "theme": theme}
        media_path = ensure_media_folder(setup, config)
        save_config(lang, theme, media_path)
        setup.destroy()
        start_main_ui(lang, theme, media_path)

    tk.Label(setup, text="🚨 Select Language / Dil Seçiniz").pack(pady=5)
    ttk.Radiobutton(setup, text="Türkçe", variable=selected_lang, value="tr").pack()
    ttk.Radiobutton(setup, text="English", variable=selected_lang, value="en").pack()

    tk.Label(setup, text="\nSelect Theme / Tema Seçiniz").pack(pady=5)
    ttk.Radiobutton(setup, text="Light / Açık", variable=selected_theme, value="light").pack()
    ttk.Radiobutton(setup, text="Dark / Koyu", variable=selected_theme, value="dark").pack()

    ttk.Button(setup, text="Save", command=confirm).pack(pady=10)
    setup.mainloop()

    # Layout - centered
    title_lbl = ttk.Label(setup, text="🚨 Select Language / Dil Seçiniz", anchor="center")
    title_lbl.pack(pady=(12, 6))

    langs_frame = ttk.Frame(setup)
    langs_frame.pack(pady=2)

    ttk.Radiobutton(langs_frame, text="Türkçe", variable=selected_lang, value="tr").pack(pady=2)
    ttk.Radiobutton(langs_frame, text="English", variable=selected_lang, value="en").pack(pady=2)

    ttk.Label(setup, text="\nSelect Theme / Tema Seçiniz").pack(pady=(8, 6))

    themes_frame = ttk.Frame(setup)
    themes_frame.pack(pady=2)

    ttk.Radiobutton(themes_frame, text="Light / Açık", variable=selected_theme, value="light").pack(pady=2)
    ttk.Radiobutton(themes_frame, text="Dark / Koyu", variable=selected_theme, value="dark").pack(pady=2)

    ttk.Button(setup, text="Save", command=confirm).pack(pady=12)
    setup.mainloop()

# -------------------------
# Main UI
# -------------------------
def start_main_ui(language, theme, media_path):
    """
    Start the main Siren UI. This function initializes pygame mixer AFTER Tk root is created.
    Hides console (Windows) once the main UI is up (so setup errors are visible earlier).
    """
    # Create root early so dialogs and parenting work; also allow hiding console after this point.
    root = tk.Tk()
    root.title("🚨 Siren App – by eyupensrr")
    # Start in fullscreen (user requested full screen)
    root.attributes("-fullscreen", True)

    # Hide console window (Windows only) now that root exists
    try:
        ctypes.windll.user32.ShowWindow(ctypes.windll.kernel32.GetConsoleWindow(), 0)
    except Exception:
        pass

    # Initialize pygame mixer now (after Tk root exists)
    try:
        pygame.mixer.init()
    except Exception as e:
        # If mixer fails, show a non-blocking warning in UI later
        print("pygame.mixer.init() failed:", e, file=sys.stderr)

    # Colors and language dict
    bg_light = "#F0F0F0"
    bg_dark = "#212121"
    bg_color = bg_dark if theme == "dark" else bg_light
    fg_color = "white" if theme == "dark" else "black"

    LANG = {
        "tr": {"mode": "Mod: ", "stop_all": "Tüm Sesleri Durdur", "horn": "Korna",
               "switch": "Geçiş", "flash": "Çakar", "exit": "Çıkış",
               "extend": "Uzatma Siren", "theme": "Tema"},
        "en": {"mode": "Mode: ", "stop_all": "Stop All Sounds", "horn": "Horn",
               "switch": "Switch", "flash": "Flash", "exit": "Exit",
               "extend": "Extended Siren", "theme": "Theme"}
    }

    root.configure(bg=bg_color)

    # -------------------------
    # Load fullscreen icon (PNG) from media_path
    # -------------------------
    fsc_icon = None
    fsc_icon_obj = None  # keep reference to avoid GC
    def load_fsc_icon():
        nonlocal fsc_icon, fsc_icon_obj
        fsc_icon = None
        fsc_icon_obj = None
        if not media_path:
            return
        icon_name = "dark_fsc.png" if theme == "dark" else "light_fsc.png"
        icon_path = os.path.join(media_path, icon_name)
        if os.path.exists(icon_path):
            try:
                if PIL_AVAILABLE:
                    img = Image.open(icon_path)
                    img = img.resize((32, 32), Image.LANCZOS)
                    fsc_icon_obj = ImageTk.PhotoImage(img)
                    fsc_icon = fsc_icon_obj
                else:
                    # fallback to Tk PhotoImage (may work for PNG in some builds)
                    fsc_icon = tk.PhotoImage(file=icon_path)
            except Exception:
                fsc_icon = None

    load_fsc_icon()

    # -------------------------
    # State variables
    # -------------------------
    current_mode = "a"  # 'a' = ARMAS, 'c' = CSR, 'z' = ZER
    current_siren = None
    last_siren_file = None
    switch_mode = False
    flash_running = False
    flash_state = {"side": "left", "rep": 0, "color": 0}
    horn_channel = pygame.mixer.Channel(5) if pygame.mixer.get_init() else None

    # Audio filename templates (exact names you provided)
    siren_files = {
        "1": "{mode}_1.ogg",
        "2": "{mode}_2.ogg",
        "3": "{mode}_3.ogg",
        "3_switch": "{mode}_4.ogg",
    }
    horn_file = "{mode}_horn.ogg"
    extend_file = "{mode}_el.ogg"

    # -------------------------
    # Audio helper functions
    # -------------------------
    def warning_text(msg):
        """Set the warning label text."""
        warning_label.config(text=msg)

    def clear_warning():
        warning_label.config(text="")

    def play_sound(full_path, loop=False):
        """Play a sound file using pygame; loop True means infinite loop."""
        nonlocal current_siren, last_siren_file, horn_channel
        if not full_path or not os.path.exists(full_path):
            warning_text(f"⚠ Missing: {os.path.basename(full_path) if full_path else 'file'}")
            return
        if not pygame.mixer.get_init():
            warning_text("⚠ Audio system not initialized")
            return
        try:
            snd = pygame.mixer.Sound(full_path)
            ch = snd.play(-1 if loop else 0)
            current_siren = (snd, ch, full_path)
            if loop:
                last_siren_file = full_path
            else:
                # non-looping sounds should not overwrite last_siren_file
                pass
            clear_warning()
        except Exception as e:
            warning_text(f"⚠ Error playing: {os.path.basename(full_path)}")

    def stop_current():
        nonlocal current_siren, last_siren_file
        if current_siren:
            _, ch, _ = current_siren
            try:
                ch.stop()
            except:
                pass
            current_siren = None
            # Do not automatically clear last_siren_file here — keep it for horn resume logic
            # But if we intentionally stop (stop_all_sounds) we'll clear last_siren_file there.

    def stop_all_sounds():
        nonlocal current_siren, last_siren_file
        try:
            pygame.mixer.stop()
        except:
            pass
        current_siren = None
        last_siren_file = None
        clear_warning()

    def toggle_siren(siren_id):
        """Toggle looping siren 1/2/3. Siren 3 respects switch_mode."""
        nonlocal switch_mode
        key = "3_switch" if (siren_id == "3" and switch_mode) else siren_id
        fname = siren_files[key].format(mode=current_mode)
        full_path = os.path.join(media_path, fname) if media_path else ""
        # If currently playing the same file -> stop it
        if current_siren and current_siren[2] == full_path:
            stop_current()
        else:
            # stop any previous and start this one looped
            stop_current()
            play_sound(full_path, loop=True)

    def toggle_switch():
        nonlocal switch_mode
        switch_mode = not switch_mode
        warning_text(f"Switch mode: {'ON' if switch_mode else 'OFF'}")
        root.after(800, clear_warning)

    def play_extend():
        stop_current()
        fname = extend_file.format(mode=current_mode)
        full_path = os.path.join(media_path, fname) if media_path else ""
        play_sound(full_path, loop=False)

    def play_horn_press(event=None):
        """Start horn (mouse press)."""
        nonlocal last_siren_file, horn_channel
        was_playing = last_siren_file
        if current_siren:
            stop_current()
        fname = horn_file.format(mode=current_mode)
        full_path = os.path.join(media_path, fname) if media_path else ""
        if full_path and os.path.exists(full_path) and pygame.mixer.get_init():
            try:
                snd = pygame.mixer.Sound(full_path)
                if horn_channel is None:
                    horn_channel_local = pygame.mixer.find_channel()
                    if horn_channel_local is not None:
                        horn_channel_local.play(snd, loops=-1)
                else:
                    horn_channel.play(snd, loops=-1)
            except:
                warning_text(f"⚠ Missing: {os.path.basename(full_path)}")
        root._horn_was_playing = was_playing

    def play_horn_release(event=None):
        """Stop horn and resume previous siren if existed."""
        nonlocal last_siren_file, horn_channel
        try:
            if horn_channel:
                horn_channel.stop()
            else:
                pygame.mixer.stop()
        except:
            pass
        was = getattr(root, "_horn_was_playing", None)
        if was:
            play_sound(was, loop=True)

    # Keyboard horn helpers
    def start_horn_key():
        """Start horn via keyboard."""
        nonlocal last_siren_file
        was_playing = last_siren_file
        if current_siren:
            stop_current()
        fname = horn_file.format(mode=current_mode)
        full_path = os.path.join(media_path, fname) if media_path else ""
        if full_path and os.path.exists(full_path) and pygame.mixer.get_init():
            try:
                snd = pygame.mixer.Sound(full_path)
                if horn_channel:
                    horn_channel.play(snd, loops=-1)
                else:
                    snd.play(loops=-1)
            except:
                warning_text(f"⚠ Missing: {os.path.basename(full_path)}")
        root._horn_was_playing = was_playing

    def stop_horn_key():
        """Stop horn started by keyboard and resume previous siren."""
        try:
            if horn_channel:
                horn_channel.stop()
            else:
                pygame.mixer.stop()
        except:
            pass
        was = getattr(root, "_horn_was_playing", None)
        if was:
            play_sound(was, loop=True)

    # Flash effect
    def toggle_flash_action():
        nonlocal flash_running
        flash_running = not flash_running
        if flash_running:
            flash_state.update({"side": "left", "rep": 0, "color": 0})
            flash_cycle()
        else:
            left_frame.configure(bg=bg_color)
            right_frame.configure(bg=bg_color)

    def flash_cycle():
        if not flash_running:
            left_frame.configure(bg=bg_color)
            right_frame.configure(bg=bg_color)
            return
        side = flash_state["side"]
        rep = flash_state["rep"]
        color = flash_state["color"]
        active_color = "red" if side == "left" else "blue"
        if color == 0:
            if side == "left":
                left_frame.configure(bg=active_color)
                right_frame.configure(bg=bg_color)
            else:
                right_frame.configure(bg=active_color)
                left_frame.configure(bg=bg_color)
            flash_state["color"] = 1
            root.after(60, flash_cycle)
        else:
            left_frame.configure(bg=bg_color)
            right_frame.configure(bg=bg_color)
            rep += 1
            if rep >= 3:
                rep = 0
                flash_state["side"] = "right" if side == "left" else "left"
            flash_state["rep"] = rep
            flash_state["color"] = 0
            root.after(60, flash_cycle)

    # Theme toggle (in-place)
    def toggle_theme_action():
        nonlocal theme, fsc_icon, fsc_icon_obj, bg_color, fg_color
        # Toggle theme value and save
        theme = "dark" if theme == "light" else "light"
        save_config(language, theme, media_path)

        # Update colors
        bg_color = bg_dark if theme == "dark" else bg_light
        fg_color = "white" if theme == "dark" else "black"

        # Apply to root and big frames
        root.configure(bg=bg_color)
        left_frame.configure(bg=bg_color)
        right_frame.configure(bg=bg_color)
        main_frame.configure(bg=bg_color)
        mode_label.config(bg=bg_color, fg=fg_color)
        warning_label.config(bg=bg_color)

        # Update fullscreen icon (if changed)
        load_fsc_icon()
        if fsc_icon:
            fs_btn.config(image=fsc_icon, bg=bg_color, activebackground=bg_color, text="")
            fs_btn.image = fsc_icon
        else:
            fs_btn.config(text="⤢", image="", bg=bg_color, activebackground=bg_color)

        # If flash is off, ensure frames match new bg
        if not flash_running:
            left_frame.configure(bg=bg_color)
            right_frame.configure(bg=bg_color)

        # Update mode label text to reflect current_mode and language translations
        mode_label.config(text=f"{LANG[language]['mode']}{'ARMAS' if current_mode=='a' else 'CSR' if current_mode=='c' else 'ZER'}")

        # show a small transient message
        warning_text(f"Theme: {theme}")
        root.after(700, clear_warning)

    # Fullscreen / cover-screen toggle
    is_fullscreen = [True]  # currently started in fullscreen True
    prev_geom = {"geom": None, "state": None}
    def toggle_fullscreen(event=None):
        """
        Enter cover-screen (borderless maximized window) when toggled on.
        Exit returns to zoomed (maximized) state to avoid tiny window bug.
        """
        nonlocal is_fullscreen, prev_geom
        if is_fullscreen[0]:
            # exit fullscreen -> set to zoomed (restore to maximized)
            try:
                root.attributes("-fullscreen", False)
                root.overrideredirect(False)
                root.state("zoomed")
            except Exception:
                # fallback: set reasonable geometry
                root.geometry("1024x768")
            is_fullscreen[0] = False
        else:
            # enter cover-screen: remove decorations and size to screen
            try:
                root.overrideredirect(True)
                width = root.winfo_screenwidth()
                height = root.winfo_screenheight()
                root.geometry(f"{width}x{height}+0+0")
            except Exception:
                pass
            is_fullscreen[0] = True

    # -------------------------
    # GUI layout (original positions)
    # -------------------------
    left_frame = tk.Frame(root, bg=bg_color)
    right_frame = tk.Frame(root, bg=bg_color)
    left_frame.grid(row=0, column=0, sticky="nsew")
    right_frame.grid(row=0, column=1, sticky="nsew")
    root.grid_columnconfigure(0, weight=1)
    root.grid_columnconfigure(1, weight=1)
    root.grid_rowconfigure(0, weight=1)

    main_frame = tk.Frame(root, padx=10, pady=10, bg=bg_color)
    main_frame.place(relx=0.5, rely=0.5, anchor="center")

    mode_label = tk.Label(main_frame, text=f"{LANG[language]['mode']}ARMAS", font=("Arial", 12, "bold"), bg=bg_color, fg=fg_color)
    mode_label.grid(row=0, column=0, columnspan=4, sticky="w")

    # Modified set_mode: preserve playing siren identity and switch it to new mode
    def set_mode(mode):
        nonlocal current_mode, last_siren_file, current_siren
        current_mode = mode
        # If there is a looping siren playing (last_siren_file), compute equivalent filename in new mode
        if last_siren_file:
            base = os.path.basename(last_siren_file)
            # detect which siren variant was playing by suffix
            target_key = None
            if base.endswith("_1.ogg"):
                target_key = "1"
            elif base.endswith("_2.ogg"):
                target_key = "2"
            elif base.endswith("_3.ogg"):
                # could be 3 or 3_switch depending on original filename name;
                # prefer 3 unless original ended with _4.ogg
                if base.endswith("_3.ogg"):
                    target_key = "3"
            elif base.endswith("_4.ogg"):
                target_key = "3_switch"
            # If found, construct new path and play it looped
            if target_key:
                fname = siren_files[target_key].format(mode=current_mode)
                full_path = os.path.join(media_path, fname) if media_path else ""
                # stop previous and start new file
                stop_current()
                play_sound(full_path, loop=True)
            else:
                # If previous playing was something else (horn/extend), just stop and not start
                stop_current()
        else:
            # nothing playing — just ensure no sounds
            stop_current()
        mode_label.config(text=f"{LANG[language]['mode']}{'ARMAS' if mode=='a' else 'CSR' if mode=='c' else 'ZER'}")

    # Mode buttons (column 0, rows 1..3)
    ttk.Button(main_frame, text="ARMAS", command=lambda: set_mode("a")).grid(row=1, column=0, padx=4, pady=4)
    ttk.Button(main_frame, text="CSR", command=lambda: set_mode("c")).grid(row=2, column=0, padx=4, pady=4)
    ttk.Button(main_frame, text="ZER", command=lambda: set_mode("z")).grid(row=3, column=0, padx=4, pady=4)

    # Siren buttons (column 1, rows 1..3)
    ttk.Button(main_frame, text="Siren 1", command=lambda: toggle_siren("1")).grid(row=1, column=1, padx=4, pady=4)
    ttk.Button(main_frame, text="Siren 2", command=lambda: toggle_siren("2")).grid(row=2, column=1, padx=4, pady=4)
    ttk.Button(main_frame, text="Siren 3", command=lambda: toggle_siren("3")).grid(row=3, column=1, padx=4, pady=4)

    # Controls (column 2 & 3 & 4 as original)
    stop_all_btn = ttk.Button(main_frame, text=LANG[language]["stop_all"], command=stop_all_sounds)
    stop_all_btn.grid(row=1, column=2, padx=4, pady=4)

    horn_btn = ttk.Button(main_frame, text=LANG[language]["horn"])
    horn_btn.grid(row=2, column=2, padx=4, pady=4)
    horn_btn.bind("<ButtonPress>", play_horn_press)
    horn_btn.bind("<ButtonRelease>", play_horn_release)

    switch_btn = ttk.Button(main_frame, text=LANG[language]["switch"], command=toggle_switch)
    switch_btn.grid(row=3, column=2, padx=4, pady=4)

    flash_btn = ttk.Button(main_frame, text=LANG[language]["flash"], command=toggle_flash_action)
    flash_btn.grid(row=2, column=3, padx=4, pady=4)

    exit_btn = ttk.Button(main_frame, text=LANG[language]["exit"], command=root.destroy)
    exit_btn.grid(row=1, column=4, padx=4, pady=4)

    extend_btn = ttk.Button(main_frame, text=LANG[language]["extend"], command=play_extend)
    extend_btn.grid(row=2, column=4, padx=4, pady=4)

    theme_btn = ttk.Button(main_frame, text=LANG[language]["theme"], command=toggle_theme_action)
    theme_btn.grid(row=3, column=4, padx=4, pady=4)

    # Warning label
    warning_label = tk.Label(main_frame, text="", font=("Arial", 9, "italic"), bg=bg_color, fg="red")
    warning_label.grid(row=4, column=0, columnspan=5, pady=8)

    if not media_path or not os.path.exists(media_path):
        warning_label.config(text="⚠ Media folder missing - sounds disabled")

    # Left/right big frames background for flash effect
    left_frame.configure(bg=bg_color)
    right_frame.configure(bg=bg_color)

    # Fullscreen small icon button (top-right) - use PNG icon if available
    if fsc_icon:
        fs_btn = tk.Button(root, image=fsc_icon, bd=0, bg=bg_color, activebackground=bg_color,
                           command=toggle_fullscreen)
        fs_btn.image = fsc_icon  # prevent garbage-collection
    else:
        fs_btn = tk.Button(root, text="⤢", font=("Arial", 12), bd=0, bg=bg_color,
                           activebackground=bg_color, command=toggle_fullscreen)
    fs_btn.place(relx=0.995, rely=0.01, anchor="ne")

    # Bind F11 to toggle cover-screen as well
    root.bind("<F11>", toggle_fullscreen)

    # Make sure root has focus to capture keys
    root.focus_force()

    # -------------------------
    # Keyboard bindings
    # -------------------------
    def on_key_press(event):
        k = event.keysym.upper()
        if k == "Q":
            set_mode("a")
        elif k == "W":
            set_mode("c")
        elif k == "E":
            set_mode("z")
        elif k == "1":
            toggle_siren("1")
        elif k == "2":
            toggle_siren("2")
        elif k == "3":
            toggle_siren("3")
        elif k == "H":
            # start horn
            start_horn_key()
        elif k == "V":
            toggle_switch()
        elif k == "S":
            stop_all_sounds()
        elif k == "L":
            toggle_flash_action()
        elif k == "I":
            play_extend()
        elif k == "T":
            toggle_theme_action()

    def on_key_release(event):
        if event.keysym.upper() == "H":
            stop_horn_key()

    root.bind_all("<KeyPress>", on_key_press)
    root.bind_all("<KeyRelease>", on_key_release)

    root.mainloop()

# -------------------------
# Program entry
# -------------------------
if __name__ == "__main__":
    cfg = load_config()
    # Try hide console early (Windows) to make setup appear without console window
    try:
        ctypes.windll.user32.ShowWindow(ctypes.windll.kernel32.GetConsoleWindow(), 0)
    except Exception:
        pass

    # If config incomplete -> run setup
    if cfg.get("language") and cfg.get("theme"):
        # Use hidden temporary root for media folder selection dialog (no visible console manipulation here)
        tmp = tk.Tk()
        tmp.withdraw()
        media_path = ensure_media_folder(tmp, cfg)
        tmp.destroy()
        start_main_ui(cfg.get("language"), cfg.get("theme"), media_path)
    else:
        setup_screen()
