import tkinter as tk
from tkinter import ttk, filedialog, messagebox
import pygame
import os
import ctypes

# --- Hide console window (Windows only) ---
try:
    ctypes.windll.user32.ShowWindow(ctypes.windll.kernel32.GetConsoleWindow(), 0)
except:
    pass

CONFIG_FILE = "config.txt"

# --- CONFIG FUNCTIONS ---
def load_config():
    """Reads user settings from config.txt or returns default values."""
    config = {"language": None, "theme": None, "media_path": None}
    if os.path.exists(CONFIG_FILE):
        with open(CONFIG_FILE, "r", encoding="utf-8") as f:
            for line in f:
                if "=" in line and not line.strip().startswith("#"):
                    key, val = line.strip().split("=", 1)
                    if key in config:
                        config[key] = val
    return config

def save_config(language, theme, media_path):
    """Saves configuration to config.txt."""
    with open(CONFIG_FILE, "w", encoding="utf-8") as f:
        f.write("# ⚠️ DO NOT EDIT THIS FILE UNLESS YOU ARE A DEVELOPER.\n")
        f.write("# Manual editing may cause issues.\n\n")
        f.write(f"language={language}\n")
        f.write(f"theme={theme}\n")
        f.write(f"media_path={media_path}\n")

# --- MEDIA FOLDER CHECK ---
def ensure_media_folder(root, config):
    """Checks if the media folder exists, asks user if not."""
    media_path = config.get("media_path") or os.path.join(os.getcwd(), "media")

    if not os.path.exists(media_path):
        messagebox.showwarning(
            "Media folder missing",
            "Media folder not found.\nPlease select your media directory.",
            parent=root
        )
        selected = filedialog.askdirectory(title="Select Media Folder", parent=root)
        if selected:
            media_path = selected
            save_config(config.get("language") or "en", config.get("theme") or "light", media_path)
        else:
            messagebox.showerror(
                "Error",
                "Media folder not selected. Sounds will not work.\nYou can select it again next time.",
                parent=root
            )
            media_path = ""
    return media_path

# --- SETUP SCREEN (first run) ---
def setup_screen():
    """Language and theme selection shown only on first launch."""
    setup = tk.Tk()
    setup.title("siren app by eyupensrr-config")
    setup.geometry("360x230")
    setup.eval('tk::PlaceWindow . center')

    selected_lang = tk.StringVar()
    selected_theme = tk.StringVar()

    def confirm():
        lang = selected_lang.get()
        theme = selected_theme.get()
        if not lang or not theme:
            messagebox.showwarning("Missing Selection", "Please select both language and theme before continuing.")
            return
        config = {"language": lang, "theme": theme}
        media_path = ensure_media_folder(setup, config)
        save_config(lang, theme, media_path)
        setup.destroy()
        start_main_ui(lang, theme, media_path)

    tk.Label(setup, text="🚨 Select Language / Dil Seçiniz").pack(pady=5)
    ttk.Radiobutton(setup, text="Türkçe", variable=selected_lang, value="tr").pack()
    ttk.Radiobutton(setup, text="English", variable=selected_lang, value="en").pack()

    tk.Label(setup, text="\nSelect Theme / Tema Seçiniz").pack(pady=5)
    ttk.Radiobutton(setup, text="Light / Açık", variable=selected_theme, value="light").pack()
    ttk.Radiobutton(setup, text="Dark / Koyu", variable=selected_theme, value="dark").pack()

    ttk.Button(setup, text="Save", command=confirm).pack(pady=10)
    setup.mainloop()

# --- MAIN APPLICATION ---
def start_main_ui(language, theme, media_path):
    """Main siren control interface."""
    pygame.mixer.init()

    root = tk.Tk()
    root.title("🚨 Siren App – by eyupensrr")
    root.attributes("-fullscreen", True)

    # --- COLORS & LANG ---
    bg_light = "#F0F0F0"
    bg_dark = "#212121"
    bg_color = bg_dark if theme == "dark" else bg_light
    fg_color = "white" if theme == "dark" else "black"

    LANG = {
        "tr": {"mode": "Mod: ", "stop_all": "Tüm Sesleri Durdur", "horn": "Korna",
               "switch": "Geçiş", "flash": "Çakar", "exit": "Çıkış",
               "extend": "Uzatma Siren", "theme": "Tema"},
        "en": {"mode": "Mode: ", "stop_all": "Stop All Sounds", "horn": "Horn",
               "switch": "Switch", "flash": "Flash", "exit": "Exit",
               "extend": "Extended Siren", "theme": "Theme"}
    }

    root.configure(bg=bg_color)

    # --- GLOBAL STATE ---
    current_mode = "a"  # a=ARMAS, c=CSR, z=ZER
    current_siren = None
    last_siren_file = None
    switch_mode = False
    flash_running = False
    flash_state = {"side": "left", "rep": 0, "color": 0}
    horn_channel = pygame.mixer.Channel(5)

    # --- AUDIO FILES ---
    siren_files = {
        "1": "{mode}_1.ogg",
        "2": "{mode}_2.ogg",
        "3": "{mode}_3.ogg",
        "3_switch": "{mode}_4.ogg",
    }
    horn_file = "{mode}_horn.ogg"
    extend_file = "{mode}_el.ogg"

    # --- AUDIO FUNCTIONS ---
    def play_sound(file_path, loop=False):
        """Play sound (looped if specified)."""
        nonlocal current_siren, last_siren_file
        if not os.path.exists(file_path):
            warning_label.config(text=f"⚠ Missing: {os.path.basename(file_path)}")
            return
        sound = pygame.mixer.Sound(file_path)
        channel = sound.play(-1 if loop else 0)
        current_siren = (sound, channel, file_path)
        if loop:
            last_siren_file = file_path
        warning_label.config(text="")

    def stop_current():
        nonlocal current_siren
        if current_siren:
            sound, channel, path = current_siren
            channel.stop()
            current_siren = None

    def stop_all_sounds():
        nonlocal current_siren, last_siren_file
        pygame.mixer.stop()
        current_siren = None
        last_siren_file = None

    def toggle_siren(siren_id):
        """Toggles siren loop sound."""
        nonlocal switch_mode
        file = siren_files["3_switch" if (siren_id == "3" and switch_mode) else siren_id].format(mode=current_mode)
        full_path = os.path.join(media_path, file)
        if current_siren and current_siren[2] == full_path:
            stop_current()
        else:
            stop_current()
            play_sound(full_path, loop=True)

    def toggle_switch():
        nonlocal switch_mode
        switch_mode = not switch_mode
        print("Switch mode:", switch_mode)

    def play_extend():
        stop_current()
        file = extend_file.format(mode=current_mode)
        full_path = os.path.join(media_path, file)
        play_sound(full_path, loop=False)

    def play_horn(event):
        """Start horn while button is pressed."""
        nonlocal current_siren, last_siren_file
        was_playing = last_siren_file
        if current_siren:
            stop_current()
        file = horn_file.format(mode=current_mode)
        full_path = os.path.join(media_path, file)
        if os.path.exists(full_path):
            sound = pygame.mixer.Sound(full_path)
            horn_channel.play(sound, loops=-1)
        event.widget.was_playing = was_playing

    def stop_horn(event):
        """Stop horn and resume last siren if existed."""
        nonlocal last_siren_file
        horn_channel.stop()
        if hasattr(event.widget, "was_playing") and event.widget.was_playing:
            play_sound(event.widget.was_playing, loop=True)

    # --- FLASH EFFECT ---
    def toggle_flash():
        nonlocal flash_running
        flash_running = not flash_running
        if flash_running:
            flash_state.update({"side": "left", "rep": 0, "color": 0})
            flash_cycle()
        else:
            left_frame.configure(bg=bg_color)
            right_frame.configure(bg=bg_color)

    def flash_cycle():
        if not flash_running:
            left_frame.configure(bg=bg_color)
            right_frame.configure(bg=bg_color)
            return

        side = flash_state["side"]
        rep = flash_state["rep"]
        color = flash_state["color"]
        active_color = "red" if side == "left" else "blue"

        if color == 0:
            if side == "left":
                left_frame.configure(bg=active_color)
                right_frame.configure(bg=bg_color)
            else:
                right_frame.configure(bg=active_color)
                left_frame.configure(bg=bg_color)
            flash_state["color"] = 1
            root.after(60, flash_cycle)
        else:
            left_frame.configure(bg=bg_color)
            right_frame.configure(bg=bg_color)
            rep += 1
            if rep >= 3:
                rep = 0
                flash_state["side"] = "right" if side == "left" else "left"
            flash_state["rep"] = rep
            flash_state["color"] = 0
            root.after(60, flash_cycle)

    # --- THEME FUNCTIONS ---
    def toggle_theme():
        new_theme = "dark" if theme == "light" else "light"
        save_config(language, new_theme, media_path)
        root.destroy()
        start_main_ui(language, new_theme, media_path)

    # --- GUI LAYOUT ---
    left_frame = tk.Frame(root, bg=bg_color)
    right_frame = tk.Frame(root, bg=bg_color)
    left_frame.grid(row=0, column=0, sticky="nsew")
    right_frame.grid(row=0, column=1, sticky="nsew")
    root.grid_columnconfigure(0, weight=1)
    root.grid_columnconfigure(1, weight=1)
    root.grid_rowconfigure(0, weight=1)

    main_frame = tk.Frame(root, padx=10, pady=10, bg=bg_color)
    main_frame.place(relx=0.5, rely=0.5, anchor="center")

    mode_label = tk.Label(main_frame, text=f"{LANG[language]['mode']}ARMAS", font=("Arial", 12, "bold"), bg=bg_color, fg=fg_color)
    mode_label.grid(row=0, column=0, columnspan=4, sticky="w")

    def set_mode(mode):
        nonlocal current_mode
        current_mode = mode
        stop_all_sounds()
        mode_label.config(text=f"{LANG[language]['mode']}{'ARMAS' if mode=='a' else 'CSR' if mode=='c' else 'ZER'}")

    # Mode buttons
    for i, (txt, mode) in enumerate([("ARMAS", "a"), ("CSR", "c"), ("ZER", "z")]):
        ttk.Button(main_frame, text=txt, command=lambda m=mode: set_mode(m)).grid(row=i+1, column=0, padx=4, pady=4)

    # Siren buttons
    for i in range(3):
        ttk.Button(main_frame, text=f"Siren {i+1}", command=lambda s=str(i+1): toggle_siren(s)).grid(row=i+1, column=1, padx=4, pady=4)

    # Control buttons
    stop_all_btn = ttk.Button(main_frame, text=LANG[language]["stop_all"], command=stop_all_sounds)
    stop_all_btn.grid(row=1, column=2, padx=4, pady=4)

    horn_btn = ttk.Button(main_frame, text=LANG[language]["horn"])
    horn_btn.grid(row=2, column=2, padx=4, pady=4)
    horn_btn.bind("<ButtonPress>", play_horn)
    horn_btn.bind("<ButtonRelease>", stop_horn)

    switch_btn = ttk.Button(main_frame, text=LANG[language]["switch"], command=toggle_switch)
    switch_btn.grid(row=3, column=2, padx=4, pady=4)

    flash_btn = ttk.Button(main_frame, text=LANG[language]["flash"], command=toggle_flash)
    flash_btn.grid(row=2, column=3, padx=4, pady=4)

    exit_btn = ttk.Button(main_frame, text=LANG[language]["exit"], command=root.destroy)
    exit_btn.grid(row=1, column=4, padx=4, pady=4)

    extend_btn = ttk.Button(main_frame, text=LANG[language]["extend"], command=play_extend)
    extend_btn.grid(row=2, column=4, padx=4, pady=4)

    theme_btn = ttk.Button(main_frame, text=LANG[language]["theme"], command=toggle_theme)
    theme_btn.grid(row=3, column=4, padx=4, pady=4)

    # Missing file / warning label
    warning_label = tk.Label(main_frame, text="", font=("Arial", 9, "italic"), bg=bg_color, fg="red")
    warning_label.grid(row=4, column=0, columnspan=5, pady=8)

    # If media folder missing, show permanent warning
    if not media_path or not os.path.exists(media_path):
        warning_label.config(text="⚠ Media folder missing - sounds disabled")

    root.mainloop()

# --- PROGRAM ENTRY ---
config = load_config()

if config["language"] and config["theme"]:
    tmp_root = tk.Tk()
    tmp_root.withdraw()
    media_path = ensure_media_folder(tmp_root, config)
    tmp_root.destroy()
    start_main_ui(config["language"], config["theme"], media_path)
else:
    setup_screen()
